version: "3.8"

services:
  postgres:
    container_name: streamingweb
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: streamingweb
      POSTGRES_DB: streamingweb

volumes:
  postgres_data:
